url: "https://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-2-Vutoni" # the subpath of your site, e.g. /blog
title: "Top 5" # the name of your site, e.g. ACME Corp.

collections:
  robots:
    output: true

plugins:
  - jekyll-admin

nav-links:
  - name: "Top Projet animation 2019"
    link: "/projets-animation"
  - name: "Top album rap 2019"
    link: "/projets-rap-2019"
